### ISSUE TITLE
Current Youtube API seems to crash pafy

### ISSUE THREAD

**Issue by orithena** [orithena/youtupi#5]
Hi @kktuax!

In case you're wondering why more and more youtube videos won't load: Upgrade pafy to v0.5.3.1.
Looks like youtube changed it's JSON output in a way that the key 'categories' may now be None after parsing, which crashes pafy 0.4.2. According to github, you do still use that old version. For youtupi, pafy 0.5.3.1 is a drop-in replacement (according to my not-very-extensive tests).

(BTW, I finally updated my fork to your changes. Nice work on the UI, I like it. But what are "Presets" for? I couldn't figure that out yet.)

**Comment by kktuax** [comment]
Hey @orithena: Thanks a lot for the support! I just cherry-picked a couple of commits and finally youtube search seems to be working perfectly again.

I'm glad to hear that you like the latest UI changes :)

Regarding the "presets": is just a way for collecting some results from a static location. In my case I use it for accessing a list of radio streams. You can find some documentation on the wiki: https://github.com/kktuax/youtupi/wiki/Presets
